### ISSUE TITLE
`npm test` error

### ISSUE THREAD

**Issue by KatieMFritz** [lansingcodes/slide#1]
@chrisvfritz I've got a fork installed locally, and after some troubleshooting*, I can use `npm run dev` to see it in my browser. So far so good.

`npm test` gives me the following output:
```shell
> lansingcodes-welcome-slide@ test C:\wamp64\www\slide
> karma start build/karma.conf.js --single-run

15 09 2017 11:46:34.213:ERROR [config]: File C:\wamp64\www\slide\build\karma.conf.js does not exist!
npm ERR! Test failed.  See above for more details.
```

Not sure what `karma.conf.js` is, but I don't see it in the repo anywhere. Should something be generating it?

*I rebuilt `node-sass` because I was getting an error with the latest version of node, and I changed `http-proxy-middleware` to `http-proxy` in `dev-server.js` because that's what the package is called in `node_modules`.

**Comment by chrisvfritz** [comment]
It looks like tests weren't generated for the project, but the script to run the tests was still added. PR welcome to remove it. 😄

**Comment by egillespie** [comment]
Closing. We need to rewrite the `slide` project from the ground up and we'll make sure the redesign is mobile-friendly.
