### ISSUE TITLE
responsive design

### ISSUE THREAD

**Issue by KatieMFritz** [lansingcodes/slide#2]
I've noticed that much of the text is often pretty small and hard to read at actual meetups (from a distance, sometimes on TV, etc.). On narrower viewports, content overlaps. 

Can I take a stab at redesigning the layout and CSS to be more responsive? Any concerns I should know about going in?

**Comment by chrisvfritz** [comment]
Yes do it please thank you. 🙂  No concerns.

**Comment by egillespie** [comment]
Here are some example URLs that can be used for testing:

* https://slide.lansing.codes/?imageUrl=http%3A%2F%2Fi.imgur.com%2F3I8942W.png&wifiPW=b5sbtdc%20%20%20wifiaccess&wifiSSID=LCCStudent#demo%20night
* https://slide.lansing.codes/?imageUrl=https%3A%2F%2Fi.imgur.com%2FXs5rbWs.png&wifiPW=MeetYourMaker2013&wifiSSID=LansingMakersNetwork#demo%20night
* https://slide.lansing.codes/?eventTitleqkzjlpyxmbpb=Demo%20night%20at%20SBDC%21%20%F0%9F%91%BE&imageUrl=https%3A%2F%2Fi.imgur.com%2FWTUwdTi.png&wifiPW=lansingfledge&wifiSSID=Fledge%20Wifi#demo%20night

**Comment by kentyunge** [comment]
@KatieMFritz I made a quick mock of a concept of the website to make it feel a little less stock bootstrap.  Personally, I don't feel like the top navigation provides much value and those sections can be discovered through user exploration.  Would be happy to discuss further or take any comments you may have.

![lansingcodes](https://user-images.githubusercontent.com/3669980/47106006-83aa7c80-d213-11e8-832a-832ef3532c4f.png)

**Comment by egillespie** [comment]
@kentyunge This looks sweet! Would you mind creating a new issue in the `www` repository and share this image in it?

What would the mockup look like if we removed the whole "Membership Organizations" section and put a whole calendar up near the top? The full calendar view draws quite a bit of traffic to the site.

**Comment by kentyunge** [comment]
@egillespie I added an issue to the www project (https://github.com/lansingcodes/www/issues/51) with an updated mockup for you to review.  Comments welcome....

**Comment by egillespie** [comment]
Closing. We need to rewrite the `slide` project from the ground up and we'll make sure the redesign is mobile-friendly.
